apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - image: paulbouwer/hello-kubernetes:1.8
        name: hello-app
        ports:
        - containerPort: 8088
          name: hello-web
        env:
        - name: PORT
          value: "8088"
        - name: MESSAGE
          value: "Greetings, SREs! Argo brought me here! REV: 2"
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
