apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  ports:
  - port: 8088
    targetPort: 8088
    name: web
  selector:
    app: hello-app
  type: LoadBalancer
