apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  labels:
    app: guestbook-ui
spec:
  ports:
  - port: 8088
    targetPort: 8088
    name: web
  selector:
    app: guestbook-ui
  type: LoadBalancer
