apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: paulbouwer/hello-kubernetes:1.8
        name: guestbook-ui
        ports:
        - containerPort: 8088
        env:
        - name: PORT
          value: "8088"
